const currencies = [
  { code: "USD", symbol: "🇺🇸", name: "Dólar Americano" },
  { code: "EUR", symbol: "🇪🇺", name: "Euro" },
  { code: "GBP", symbol: "🇬🇧", name: "Libra Esterlina" },
  { code: "JPY", symbol: "🇯🇵", name: "Iene Japonês" },
  { code: "AUD", symbol: "🇦🇺", name: "Dólar Australiano" },
  { code: "CAD", symbol: "🇨🇦", name: "Dólar Canadense" },
  { code: "CHF", symbol: "🇨🇭", name: "Franco Suíço" },
  { code: "CNY", symbol: "🇨🇳", name: "Yuan Chinês" },
  { code: "SEK", symbol: "🇸🇪", name: "Coroa Sueca" },
  { code: "NZD", symbol: "🇳🇿", name: "Dólar Neozelandês" },
  { code: "MXN", symbol: "🇲🇽", name: "Peso Mexicano" },
  { code: "SGD", symbol: "🇸🇬", name: "Dólar de Singapura" },
  { code: "HKD", symbol: "🇭🇰", name: "Dólar de Hong Kong" },
  { code: "NOK", symbol: "🇳🇴", name: "Coroa Norueguesa" },
  { code: "KRW", symbol: "🇰🇷", name: "Won Sul-Coreano" },
  { code: "TRY", symbol: "🇹🇷", name: "Lira Turca" },
  { code: "RUB", symbol: "🇷🇺", name: "Rublo Russo" },
  { code: "INR", symbol: "🇮🇳", name: "Rúpia Indiana" },
  { code: "BRL", symbol: "🇧🇷", name: "Real Brasileiro" },
  { code: "ZAR", symbol: "🇿🇦", name: "Rand Sul-Africano" },
  { code: "ARS", symbol: "🇦🇷", name: "Peso Argentino" },
  { code: "CLP", symbol: "🇨🇱", name: "Peso Chileno" },
  { code: "COP", symbol: "🇨🇴", name: "Peso Colombiano" },
  { code: "PEN", symbol: "🇵🇪", name: "Sol Peruano" },
  { code: "THB", symbol: "🇹🇭", name: "Baht Tailandês" },
  { code: "IDR", symbol: "🇮🇩", name: "Rupia Indonésia" },
];

export default currencies;
